### ISSUE TITLE
Class vs Functional Components

### ISSUE THREAD

**Issue by tanelam** [dhamilton47/jammming#4]
https://github.com/dhamilton47/jammming/blob/f21b169ee49b76b8b800b3409783d85089d31e1b/src/components/SearchResults/SearchResults.js#L5-L21

React Components can be declared both as classes and as functions. Functional components are simpler to define but they lack certain features currently available only to class components, and I suggest you use them unless you need state. You can find more info [here](https://reactjs.org/docs/components-and-props.html)!

```
const SearchResults = props => {
//		console.log('SearchResults: ', props.onAdd);
	return (
		<div className="SearchResults">
			<h2>Results</h2>

			<TrackList
				tracks={props.tracks}
				onAdd={props.onAdd}
				isRemoval={false}
			/>
		</div>

	);
}


```

**Comment by dhamilton47** [comment]
Good to know.  Thank you.
